/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fITlhHMHZZy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import {FiUpload} from "react-icons/fi"

export function cv() {
  return (
    (<div className="flex items-center justify-center h-screen">
      <div>
        <div className="w-full max-w-md">
          <div className="text-center">
            <div className="font-bold">Upload Your Resume</div>
            <div>Drag and drop your resume or click the upload button to submit.</div>
          </div>
          <div>
            <br></br>
          </div>
          <div>
            <div
              className="flex h-48  w-100 items-center justify-center rounded-md border-2 border-dashed border-gray-300 px-6 py-10 transition-colors hover:border-gray-400 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2">
              <div className="text-center">
                <FiUpload className="mx-auto h-12 w-12 text-gray-400" />
                <p className="mt-2 text-sm font-medium text-gray-900">Drag and drop your resume</p>
                <p className="mt-1 text-sm text-gray-500">or click to upload</p>
              </div>
            </div>
          </div>
          <div>
            <div>
              <br></br>
            </div>
            <Button className="w-full mx-auto bg-black text-white" variant="primary">
              Upload
            </Button>
          </div>
        </div>
      </div>
    </div>)
  );
}


