/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fT8Qvig1rn8
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import React from "react";

export function Login() {
  return (
    (<div
      className="flex h-screen w-full items-center justify-center bg-white">
      <div
        className="w-full max-w-md space-y-6 rounded-lg bg-white p-6 shadow-lg ">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Login</h1>
          <p className="text-gray-500 dark:text-gray-400">Enter your username and password </p>
        </div>
        <form className="space-y-4">
          <div>
            <Label htmlFor="username">Username</Label>
            <Input
              className="mt-1"
              id="username"
              placeholder="Enter your username"
              type="text" />
          </div>
          <div>
            <div className="flex items-center justify-between">
              <Label htmlFor="password">Password</Label>
              <Link
                className="text-sm font-small text-gray-600 hover:underline dark:text-gray-400"
                href="#">
                Forgot Password?
              </Link>
            </div>
            <Input
              className="mt-1"
              id="password"
              placeholder="Enter your password"
              type="password" />
          </div>
          <Button className="w-full mx-auto bg-black text-white" type="submit">
            Login
          </Button>
        </form>
      </div>
    </div>)
  );
}
