/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8afHrIU8t4c
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Register() {
  return (
    (<div
      className="w-full h-full h-screen max-w-md mx-auto py-20 px-4 sm:px-6 lg:px-8 bg-white dark:bg-white">
      <div className="space-y-6">
        <div className="text-center">
          <h1
            className="text-4xl font-bold tracking-tight text-gray-900 dark:text-gray-900">Create an Account</h1>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-600">Enter your details to get started.</p>
        </div>
        <div className="bg-white dark:bg-white shadow-lg rounded-lg overflow-hidden">
          <div className="px-6 py-8 sm:px-10">
            <form action="#" className="space-y-6" method="POST">
              <div>
                <label
                  className="block text-sm font-medium text-gray-700 dark:text-gray-700"
                  htmlFor="name">
                  Full Name
                </label>
                <div className="mt-1">
                  <input
                    autoComplete="name"
                    className="block w-full px-3 py-2 border border-gray-200 border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-white dark:border-gray-600 dark:text-gray-700 dark:border-gray-800"
                    id="name"
                    name="name"
                    placeholder="John Doe"
                    required
                    type="text" />
                </div>
              </div>
              <div>
                <label
                  className="block text-sm font-medium text-gray-700 dark:text-gray-700"
                  htmlFor="phone">
                  Phone Number
                </label>
                <div className="mt-1">
                  <input
                    autoComplete="tel"
                    className="block w-full px-3 py-2 border border-gray-200 border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-white dark:border-gray-600 dark:text-gray-700 dark:border-gray-800"
                    id="phone"
                    name="phone"
                    placeholder="+1 (555) 555-5555"
                    required
                    type="tel" />
                </div>
              </div>
              <div>
                <label
                  className="block text-sm font-medium text-gray-700 dark:text-gray-700"
                  htmlFor="email">
                  Email address
                </label>
                <div className="mt-1">
                  <input
                    autoComplete="email"
                    className="block w-full px-3 py-2 border border-gray-200 border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm dark:bg-white dark:border-gray-600 dark:text-gray-700 dark:border-gray-800"
                    id="email"
                    name="email"
                    placeholder="john@example.com"
                    required
                    type="email" />
                </div>
              </div>
              <div>
                <button
                  className="w-full flex justify-center py-2 px-4 border border-gray-200 border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-black hover:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-950 dark:bg-black dark:hover:bg-gray-900 dark:border-gray-800"
                  type="submit">
                  Create Account
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>)
  );
}
