/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Glw26ObgUTB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function settings() {
  return (
    (<div className="max-w-2xl mx-auto p-6 sm:p-8">
      <h1 className="text-2xl font-bold mb-6">Account Settings</h1>
      <form className="space-y-6">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          <div>
            <Label htmlFor="fullName">Full Name</Label>
            <Input id="fullName" placeholder="Enter your full name" type="text" />
          </div>
          <div>
            <Label htmlFor="email">Email Address</Label>
            <Input id="email" placeholder="Enter your email address" type="email" />
          </div>
        </div>
        <div>
          <Label htmlFor="emailPassword">Email Password</Label>
          <Input
            id="emailPassword"
            placeholder="Enter your email password"
            type="password" />
        </div>
        <div>
          <Label htmlFor="phoneNumber">Phone Number</Label>
          <Input id="phoneNumber" placeholder="Enter your phone number" type="tel" />
        </div>
        <div>
          <Label htmlFor="linkedIn">LinkedIn</Label>
          <Input id="linkedIn" placeholder="Enter your LinkedIn profile URL" type="url" />
        </div>
        <div className="flex justify-between items-center">
          <p className="text-gray-500">Make sure to save your changes.</p>
          <div className="flex gap-2">
            <Button className="bg-black hover:bg-gray-900 text-white" type="submit">
              Save Changes
            </Button>
          </div>
        </div>
      </form>
    </div>)
  );
}
